In [45]:
import pandas as pd
import requests
import time
import os
import logging
from scrapy import Selector
from scrapy.crawler import CrawlerProcess
import scrapy
import boto3
from dotenv import load_dotenv
import numpy as np
from fake_useragent import UserAgent

In [ ]:
load_dotenv()
AWS_KEY = os.environ["AWS_KEY"]
AWS_SECRET_KEY = os.environ["AWS_SECRET_KEY"]
BUCKET = os.environ["BUCKET"]
API_Key = os.environ["OWM_Token"]

In [47]:
data_path = {
    "gps" : "data_gps_26.csv",
    "weather" : "data_weather_26.csv",
    "booking" : "data_booking_26.csv"
}

possible_destination = ["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]

# Weather API Data

In [48]:
#redefining agent

user_agent_list = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
]

user_agent = user_agent_list[0]

In [49]:
#Acquisition of coordinates of the cities looked into

gps_url =    "https://nominatim.openstreetmap.org/"
target = "search"

data_gps = {}

for city in possible_destination:
    gps_data = requests.get(gps_url+target, params={"q" : f"{city}, France", "format" : "json"}, headers= {"User-Agent" : user_agent})
    time.sleep(1.01)
    if len(gps_data.json()) > 0:
        data_city = gps_data.json()[0]
        data_gps[city] = {
            "lat" : data_city['lat'],
            "lon" : data_city['lon']
        }

    else:
        print(f"No data for {city}")
data_gps

{'Mont Saint Michel': {'lat': '48.6359541', 'lon': '-1.5114600'},
 'St Malo': {'lat': '48.6495180', 'lon': '-2.0260409'},
 'Bayeux': {'lat': '49.2764624', 'lon': '-0.7024738'},
 'Le Havre': {'lat': '49.4938975', 'lon': '0.1079732'},
 'Rouen': {'lat': '49.4404591', 'lon': '1.0939658'},
 'Paris': {'lat': '48.8534951', 'lon': '2.3483915'},
 'Amiens': {'lat': '49.8941708', 'lon': '2.2956951'},
 'Lille': {'lat': '50.6365654', 'lon': '3.0635282'},
 'Strasbourg': {'lat': '48.5846140', 'lon': '7.7507127'},
 'Chateau du Haut Koenigsbourg': {'lat': '48.2493820', 'lon': '7.3439412'},
 'Colmar': {'lat': '48.0777517', 'lon': '7.3579641'},
 'Eguisheim': {'lat': '48.0447968', 'lon': '7.3079618'},
 'Besancon': {'lat': '47.2380222', 'lon': '6.0243622'},
 'Dijon': {'lat': '47.3215806', 'lon': '5.0414701'},
 'Annecy': {'lat': '45.8992348', 'lon': '6.1288847'},
 'Grenoble': {'lat': '45.1875602', 'lon': '5.7357819'},
 'Lyon': {'lat': '45.7578137', 'lon': '4.8320114'},
 'Gorges du Verdon': {'lat': '43.7496562', 'lon': '6.3285616'},
 'Bormes les Mimosas': {'lat': '43.1506968', 'lon': '6.3419285'},
 'Cassis': {'lat': '43.2140359', 'lon': '5.5396318'},
 'Marseille': {'lat': '43.2961743', 'lon': '5.3699525'},
 'Aix en Provence': {'lat': '43.5298424', 'lon': '5.4474738'},
 'Avignon': {'lat': '43.9492493', 'lon': '4.8059012'},
 'Uzes': {'lat': '44.0121279', 'lon': '4.4196718'},
 'Nimes': {'lat': '43.8374249', 'lon': '4.3600687'},
 'Aigues Mortes': {'lat': '43.5661521', 'lon': '4.1915400'},
 'Saintes Maries de la mer': {'lat': '43.4515922', 'lon': '4.4277202'},
 'Collioure': {'lat': '42.5250500', 'lon': '3.0831554'},
 'Carcassonne': {'lat': '43.2130358', 'lon': '2.3491069'},
 'Ariege': {'lat': '42.9455368', 'lon': '1.4065544'},
 'Toulouse': {'lat': '43.6044638', 'lon': '1.4442433'},
 'Montauban': {'lat': '44.0175835', 'lon': '1.3549991'},
 'Biarritz': {'lat': '43.4832523', 'lon': '-1.5592776'},
 'Bayonne': {'lat': '43.4945144', 'lon': '-1.4736657'},
 'La Rochelle': {'lat': '46.1597320', 'lon': '-1.1515951'}}

In [7]:
# gps_df = pd.DataFrame(city_gps).pivot_table()

#.to_csv(data_path["gps"])

In [ ]:
#From the GPS data, we can access the weather data to obtain the prediction for the next week.

params = {"units" : "metric",
          "exclude": "hourly, current, minutely, alerts"}

weather_ls = []
for key, value in data_gps.items():
    #time.sleep(1.02)
    url = f"https://api.openweathermap.org/data/2.5/forecast?lat={value['lat']}&lon={value['lon']}&appid={API_Key}"
    data = requests.get(url=url, params=params).json()["list"]
    for elem in data:
        if "rain" in elem.keys():
            rain = elem["rain"]["3h"]
        else:
            rain = 0

        weather_ls.append({
            "city" : key,
            "date" : pd.to_datetime(elem["dt"], unit='s', utc = True).date(),
            "cloudiness" : elem["clouds"]["all"],
            "temp_min": elem["main"]["temp_min"],
            "temp_max" : elem["main"]["temp_max"],
            "humidity" : elem["main"]["humidity"],
            "pop" : elem.get("pop", 0),
            "rain" : rain

        })


data_weather = pd.DataFrame(weather_ls)
data_weather

,city,date,cloudiness,temp_min,temp_max,humidity,pop,rain
0,Mont Saint Michel,2026-02-09,100,8.01,8.85,88,0.29,0.39
1,Mont Saint Michel,2026-02-09,100,8.57,9.06,92,1.00,4.05
2,Mont Saint Michel,2026-02-09,100,10.32,10.32,96,1.00,1.95
3,Mont Saint Michel,2026-02-09,94,9.13,9.13,96,0.76,0.42
4,Mont Saint Michel,2026-02-10,97,10.15,10.15,92,1.00,2.74
...,...,...,...,...,...,...,...,...
1395,La Rochelle,2026-02-13,46,7.67,7.67,83,0.45,0.26
1396,La Rochelle,2026-02-14,73,6.05,6.05,81,0.28,0.20
1397,La Rochelle,2026-02-14,100,5.23,5.23,73,0.20,0.12
1398,La Rochelle,2026-02-14,81,4.52,4.52,69,0.00,0.00
1399,La Rochelle,2026-02-14,2,4.86,4.86,68,0.00,0.00

In [ ]:
data_gps_df = pd.DataFrame(data_gps)
mean_weather = data_weather.drop("date", axis=1).groupby("city").mean().sort_values("temp_max", ascending=False)
mean_weather = mean_weather.reset_index().merge(data_gps_df.transpose().reset_index().rename(columns={"index":"city"}), on="city", how="left", validate="1:1")
mean_weather["size"] = (mean_weather["temp_max"]-mean_weather["temp_max"].min())/(mean_weather["temp_max"].max()-mean_weather["temp_max"].min())
mean_weather["temp_mean"] = (mean_weather["temp_max"]+mean_weather["temp_max"])/2
best_weather = mean_weather.head(5)
best_weather

In [58]:
best_weather["city"]

0                    Biarritz
1                   Marseille
2                     Bayonne
3                   Collioure
4    Saintes Maries de la mer
Name: city, dtype: object

In [ ]:
data_weather.to_csv(data_path["weather"])

Scrapping of booking

necessary information:
- Nombre de nuits
- Nombre de personnes
- dates

In [12]:
#start_urls = "https://www.imdb.com/chart/boxoffice"
# base_url = "https://www.booking.com/searchresults.html?ss=Lyon"
base_url = "https://www.booking.com/hotel/fr/le-relais-saint-michel.fr.html?aid=356980&label=mkt123sc-9ae2f832-8959-47ab-9b0f-3440cd416970&sid=53174f83b56b159e3a4977053ec251e9&all_sr_blocks=23079515_93716278_0_1_0&checkin=2026-02-17&checkout=2026-02-19&dist=0&group_adults=2&group_children=0&hapos=5&highlighted_blocks=23079515_93716278_0_1_0&hpos=5&matching_block_id=23079515_93716278_0_1_0&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&sr_pri_blocks=23079515_93716278_0_1_0__49500&srepoch=1770131460&srpvid=ec3baffc890a6439cbfdf35d5b4a5633&type=total&ucfs=1&"




headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3 ',
    "Accept-Language": "fr-FR,fr;q=0.9"
}
url = base_url.split('.html')[0]
print(url)
r = requests.get(url, headers=headers)
print(r.status_code)
response = Selector(text=r.text)

https://www.booking.com/hotel/fr/le-relais-saint-michel.fr
202

In [29]:
base_url.split('?')[0]

'https://www.booking.com/hotel/fr/le-relais-saint-michel.fr.html'

form_booking = response.css("div[data-testid='property-card-container']")
name = form_booking.css("div[data-testid='title']::text").getall()
url = form_booking.css("a[data-testid='title-link']::attr(href)").getall()
score = form_booking.css("div[data-testid='review-score']")
close = score.css("div[aria-hidden='False']")
review_score = score.css("div[aria-hidden]::text").getall()
description = form_booking.css("div[class='fff1944c52']::text").getall()
loc = form_booking.css("span[data-testid='address']::text").getall()
#Location can be improved by looking at the hotel page directly. to be done later.

In [65]:
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"

HEADERS = {
    "User-Agent": "hotel-location-demo/1.0 (dubos.john@hotmail.fr)"
}

def get_hotel_location(hotel_name, city=None, country=None):
    """
    Returns best match location data for a hotel name using OpenStreetMap Nominatim.
    """

    query = hotel_name
    if country:
        query += f", {city}, {country}"

    params = {
        "q": query,
        "format": "json",
        "limit": 1,
        "addressdetails": 1
    }

    response = requests.get(
        NOMINATIM_URL,
        params=params,
        headers=HEADERS,
        timeout=10
    )
    response.raise_for_status()

    results = response.json()
    if not results:
        return None

    r = results[0]

    return {
        "name": hotel_name,
        "latitude": float(r["lat"]),
        "longitude": float(r["lon"]),
        "display_name": r["display_name"],
        "address": r.get("address", {})
    }

In [66]:
base_url = "https://www.booking.com/searchresults.html?"

user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:143.0) Gecko/20100101 Firefox/143.0 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'
ua = UserAgent(platforms="desktop", min_version=120.0)
headers = {
    'User-Agent': user_agent,
    "Accept-Language": "fr-FR,fr;q=0.9"
}

hotel_city = {}
data_booking = []
response_ls = {}
r_ls = {}
visited = []
for city in best_weather["city"]:
    visited.append(city)
    params = {
        "ss" : city.replace(' ', '+'),
        "checkin" : "2026-02-17",
        "checkout" : "2026-02-19",
        "group_adults" : 2,
        "no_rooms" : 1,
        "group_children" : 0,
        "dest_type" : "city"
    }
    
    r = requests.get(base_url, params=params, headers= {
            'User-Agent' : ua.random, 
            "Accept-Language": "fr-FR,fr;q=0.9",
            "Connection": "keep-alive",
            "Upgrade-Insecure-Requests": "1",
            "Referer": "https://www.google.com/"})
    while r.status_code !=200:
        del r
        r = requests.get(base_url, params=params, headers= {
            'User-Agent' : ua.random, 
            "Accept-Language": 
            "fr-FR,fr;q=0.9",
            "Connection": "keep-alive",
            "Upgrade-Insecure-Requests": "1",
            "Referer": "https://www.google.com/"})
        time.sleep(1+np.random.rand())
    print(r.url)
    print(r.status_code)
    
    response = Selector(text=r.text)
    r_ls[city] = r
    response_ls[city] = response
    form_booking = response.css("div[data-testid='property-card']")
    for form in form_booking:
        name = form.css("div[data-testid='title']::text").get().split(',')[0].split('-')[0]
        url = form.css("a[data-testid='title-link']::attr(href)").get()
        score = form.css("div[data-testid='review-score']")
        close = score.css("div[aria-hidden='False']")
        review_score = score.css("div[aria-hidden]::text").get()
        description = form.css("div[class='fff1944c52']::text").get()

        hotel_info = get_hotel_location(name, city=city, country="France")
        time.sleep(1)


        # r_loc = requests.get(url=url.split('?')[0], headers={
        #     'User-Agent' : ua.random, 
        #     "Accept-Language": 
        #     "fr-FR,fr;q=0.9",
        #     "Connection": "keep-alive",
        #     "Upgrade-Insecure-Requests": "1",
        #     "Referer": "https://www.google.com/"
        # })
        # print(r_loc.url)
        # print(r_loc.status_code)
        # time.sleep(1+np.random.rand())
        # response_loc = Selector(text=r_loc.text)
        # content = response_loc.css("div[data-testid='map-entry-point-desktop-wrapper']::attr(data-atlas-latlng)").get()
        # lat = None
        # lon = None
        # if content:
        #     lat, lon = content.split(',')
        # loc = form.css("span[data-testid='address']::text").get()
        # description = [txt for txt in description if "Hébergement géré par un particulier" not in txt]

        if hotel_info is not None:
            data_booking.append({
                "city" : city,
                "name" : name,
                "url" : url,
                "review_score" : review_score,
                "description" : description,
                "location" : hotel_info["address"],
                "lat": hotel_info["latitude"],
                "lon":hotel_info["longitude"]
            })
        else:
            data_booking.append({
                "city" : city,
                "name" : name,
                "url" : url,
                "review_score" : review_score,
                "description" : description,
                "location" : "missing value",
                "lat": None,
                "lon": None
            })


hotel_df = (pd.DataFrame(data_booking))

https://www.booking.com/searchresults.html?ss=Biarritz&checkin=2026-02-17&checkout=2026-02-19&group_adults=2&no_rooms=1&group_children=0&dest_type=city
200
https://www.booking.com/searchresults.html?ss=Marseille&checkin=2026-02-17&checkout=2026-02-19&group_adults=2&no_rooms=1&group_children=0&dest_type=city
200
https://www.booking.com/searchresults.html?ss=Bayonne&checkin=2026-02-17&checkout=2026-02-19&group_adults=2&no_rooms=1&group_children=0&dest_type=city
200
https://www.booking.com/searchresults.html?ss=Collioure&checkin=2026-02-17&checkout=2026-02-19&group_adults=2&no_rooms=1&group_children=0&dest_type=city
200
https://www.booking.com/searchresults.html?ss=Saintes%2BMaries%2Bde%2Bla%2Bmer&checkin=2026-02-17&checkout=2026-02-19&group_adults=2&no_rooms=1&group_children=0&dest_type=city
200

In [62]:
len(visited)

5

In [68]:
hotel_df = pd.DataFrame(data_booking)
hotel_df.to_csv(data_path["booking"])
hotel_df

,city,name,url,review_score,description,location,lat,lon
0,Biarritz,Hôtel Barnea,https://www.booking.com/hotel/fr/hotelargieder...,"8,9",1 grand lit double,missing value,NaN,NaN
1,Biarritz,Le Talaia Hôtel & Spa Biarritz,https://www.booking.com/hotel/fr/radisson-blu-...,"8,8",1 lit simple,"{'tourism': 'Le Talaia Hôtel & Spa Biarritz', ...",43.478210,-1.564422
2,Biarritz,Hôtel Kemaris,https://www.booking.com/hotel/fr/best-western-...,"8,4",1 grand lit double,"{'tourism': 'Hôtel Best Western Kemaris', 'roa...",43.476518,-1.562496
3,Biarritz,ALFRED HOTELS Les Halles,https://www.booking.com/hotel/fr/hotelanjou.fr...,"9,1",1 grand lit double,missing value,NaN,NaN
4,Biarritz,Hôtel du Palais Biarritz,https://www.booking.com/hotel/fr/hoteldupalais...,"9,5",2 lits simples,"{'tourism': 'Hôtel du Palais', 'road': 'Avenue...",43.486435,-1.556328
...,...,...,...,...,...,...,...,...
122,Saintes Maries de la mer,Hôtel Le Neptune en Camargue,https://www.booking.com/hotel/fr/le-neptune-en...,"8,4",Hébergement géré par un particulier,missing value,NaN,NaN
123,Saintes Maries de la mer,Le Sauvage,https://www.booking.com/hotel/fr/le-sauvage-le...,"9,3",Hébergement géré par un particulier,missing value,NaN,NaN
124,Saintes Maries de la mer,De l'eau et des oiseaux !,https://www.booking.com/hotel/fr/de-l-eau-et-d...,"8,8",Hébergement géré par un particulier,missing value,NaN,NaN
125,Saintes Maries de la mer,Hôtel Spa Mas des Rièges,https://www.booking.com/hotel/fr/mas-des-riege...,"9,0","2 lits (1 canapé-lit, 1 grand lit double)",missing value,NaN,NaN
126,Saintes Maries de la mer,Résidence L'Oiseau des Mers,https://www.booking.com/hotel/fr/residence-l-o...,"9,9",1 grand lit double,missing value,NaN,NaN

In [ ]:
class BookingSpider(scrapy.Spider):
    name = "Booking_data"
    start_urls = ["https://www.booking.com/"]

    def parse(response):
        hotels = response.css("div[data-testid='title']")
        for hotel in hotels:
            yield {
                "hotel_name" : hotel.css("div::text")
            }
        return response

In [51]:
!scrapy crawl Booking_data

test
[<Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>, <Selector query="descendant-or-self::div[@data-testid = 'property-card-container']" data='<div class="aa97d6032f" data-testid="...'>]

2025-09-12 18:05:25 [scrapy.utils.log] INFO: Scrapy 2.13.3 started (bot: tutorial)
2025-09-12 18:05:26 [scrapy.utils.log] INFO: Versions:
{'lxml': '5.3.0',
 'libxml2': '2.13.8',
 'cssselect': '1.2.0',
 'parsel': '1.8.1',
 'w3lib': '2.1.2',
 'Twisted': '24.11.0',
 'Python': '3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, '
           '16:37:03) [MSC v.1929 64 bit (AMD64)]',
 'pyOpenSSL': '25.1.0 (OpenSSL 3.0.17 1 Jul 2025)',
 'cryptography': '45.0.5',
 'Platform': 'Windows-11-10.0.26100-SP0'}
2025-09-12 18:05:26 [scrapy.addons] INFO: Enabled addons:
[]
2025-09-12 18:05:26 [asyncio] DEBUG: Using selector: SelectSelector
2025-09-12 18:05:26 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2025-09-12 18:05:26 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.windows_events._WindowsSelectorEventLoop
2025-09-12 18:05:26 [scrapy.extensions.telnet] INFO: Telnet Password: bee971521fe2b05d
2025-09-12 18:05:26 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-09-12 18:05:26 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'tutorial',
 'CONCURRENT_REQUESTS_PER_DOMAIN': 1,
 'DOWNLOAD_DELAY': 1,
 'FEED_EXPORT_ENCODING': 'utf-8',
 'NEWSPIDER_MODULE': 'tutorial.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['tutorial.spiders'],
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3 '}
2025-09-12 18:05:26 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'rotating_proxies.middlewares.BanDetectionMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-09-12 18:05:26 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.start.StartSpiderMiddleware',
 'scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-09-12 18:05:26 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-09-12 18:05:26 [scrapy.core.engine] INFO: Spider opened
2025-09-12 18:05:26 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-09-12 18:05:26 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2025-09-12 18:05:26 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.booking.com/robots.txt> (referer: None)
2025-09-12 18:05:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.booking.com/searchresults.html?ss=Lyon> (referer: None)
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'InterContinental Lyon - Hotel Dieu by IHG', 'hotel_url': 'https://www.booking.com/hotel/fr/intercontinental-hotels-lyon-dieu.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=1&hapos=1&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'OKKO Hotels Lyon Centre', 'hotel_url': 'https://www.booking.com/hotel/fr/okko-hotels-lyon-pont-lafayette.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=2&hapos=2&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Boscolo Lyon Hotel & Spa', 'hotel_url': 'https://www.booking.com/hotel/fr/boscolo-exedra-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=3&hapos=3&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Radisson Blu Hotel, Lyon', 'hotel_url': 'https://www.booking.com/hotel/fr/radisson-blu-hotel-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=4&hapos=4&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Warwick Reine Astrid - Lyon', 'hotel_url': 'https://www.booking.com/hotel/fr/la-reine-astrid.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=5&hapos=5&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': "Hôtel de l'Abbaye Lyon - Boutique Hôtel", 'hotel_url': 'https://www.booking.com/hotel/fr/de-l-39-abbaye-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=6&hapos=6&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Pullman Lyon', 'hotel_url': 'https://www.booking.com/hotel/fr/pullman-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=7&hapos=7&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Carlton Hotel Lyon - MGallery Collection', 'hotel_url': 'https://www.booking.com/hotel/fr/carlton-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=8&hapos=8&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Hotel De Verdun 1882, BW Signature Collection', 'hotel_url': 'https://www.booking.com/hotel/fr/de-verdun-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=9&hapos=9&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Novotel Lyon Centre-Confluence Bord de Saone', 'hotel_url': 'https://www.booking.com/hotel/fr/novotel-lyon-confluence.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=10&hapos=10&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Hôtel Fort St Laurent Lyon - Handwritten Collection', 'hotel_url': 'https://www.booking.com/hotel/fr/et-spa-fort-st-laurent-lyon-handwritten-collection.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=11&hapos=11&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Mercure Lyon Centre Saxe Lafayette', 'hotel_url': 'https://www.booking.com/hotel/fr/mercure-grand-saxe-lafayette.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=12&hapos=12&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Hôtel Le Roosevelt Lyon', 'hotel_url': 'https://www.booking.com/hotel/fr/hotelrooseveltlyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=13&hapos=13&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Bayard Bellecour', 'hotel_url': 'https://www.booking.com/hotel/fr/bayard-bellecour.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=14&hapos=14&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Fourvière Hôtel', 'hotel_url': 'https://www.booking.com/hotel/fr/fourviere.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=15&hapos=15&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Campanile Lyon Centre Part-Dieu', 'hotel_url': 'https://www.booking.com/hotel/fr/campanile-lyon-centre-forum-part-dieu.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=16&hapos=16&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Villa Florentine', 'hotel_url': 'https://www.booking.com/hotel/fr/villaflorentine.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=17&hapos=17&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Mercure Lyon Centre Beaux-Arts', 'hotel_url': 'https://www.booking.com/hotel/fr/lyon-beaux-arts.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=18&hapos=18&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Bikube Lyon', 'hotel_url': 'https://www.booking.com/hotel/fr/bikube-lyon-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=19&hapos=19&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Honorê - Suites Bellecour', 'hotel_url': 'https://www.booking.com/hotel/fr/appartements-bellecour-a-riva-lofts-amp-suites.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=20&hapos=20&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'MHL - Maison Hotel Lyon', 'hotel_url': 'https://www.booking.com/hotel/fr/mhl-maison-hotel-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=21&hapos=21&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Lyon Marriott Hotel Cité Internationale', 'hotel_url': 'https://www.booking.com/hotel/fr/marriott-lyon.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=22&hapos=22&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'Hôtel Des Artistes', 'hotel_url': 'https://www.booking.com/hotel/fr/des-artistes.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=23&hapos=23&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from_sustainable_property_sr=1&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': 'TRIBE Lyon Croix Rousse', 'hotel_url': 'https://www.booking.com/hotel/fr/tribe-lyon-croix-rousse.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=24&hapos=24&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.booking.com/searchresults.html?ss=Lyon>

{'hotel_name': "L'AUBELYNE - Chic T2 quartier préfecture", 'hotel_url': 'https://www.booking.com/hotel/fr/aubelyne-chic-t2-quartier-prefecture.en-gb.html?aid=304142&label=gen173nr-10CAQoggJCC3NlYXJjaF9seW9uSDNYBGhNiAEBmAEzuAEXyAEM2AED6AEB-AEBiAIBqAIBuALGiZHGBsACAdICJDZjMDAxYWIwLTgwYjItNDhlOC05ZTAwLTUxMWEyODdmYzc1ZNgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=25&hapos=25&sr_order=popularity&srpvid=f460712383520564&srepoch=1757693128&from=searchresults'}
2025-09-12 18:05:29 [scrapy.core.engine] INFO: Closing spider (finished)
2025-09-12 18:05:29 [scrapy.extensions.feedexport] INFO: Stored json feed (25 items) in: results.json
2025-09-12 18:05:29 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1105,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 230583,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'elapsed_time_seconds': 2.735932,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2025, 9, 12, 16, 5, 29, 74777, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 1606438,
 'httpcompression/response_count': 2,
 'item_scraped_count': 25,
 'items_per_minute': 750.0,
 'log_count/DEBUG': 30,
 'log_count/INFO': 11,

Loading all data on the datalake (S3)

In [46]:
session = boto3.Session(aws_access_key_id = AWS_KEY, 
                        aws_secret_access_key = AWS_SECRET_KEY, 
                        region_name = "eu-west-3")

s3 = session.resource("s3")

In [52]:
my_bucket = s3.Bucket(BUCKET)
for path in data_path.values():
    my_bucket.upload_file(path, f"S3_{path}")